spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    #    url: jdbc:mysql://127.0.0.1:3306/auth_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    #url: jdbc:mysql://10.2.47.29:3306/authentication_schema?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 1111
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1024
        max-wait: 1000ms
        max-idle: 200
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms
    database: 2


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ylj.blog.entity